name: Deploy VitePress Site

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js v22.14.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.14

      - name: Install dependencies
        run: npm install

      - name: Build VitePress
        run: npm run build  # 确保 package.json 中定义了 build 命令

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist  # 根据你的构建输出目录调整
          keep_files: false